<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="0" passed="0">
	<reporter-output>
	</reporter-output>
	<suite name="Default suite" duration-ms="13" started-at="2018-01-20T04:02:48Z"
		finished-at="2018-01-20T04:02:48Z">
		<groups>
		</groups>
		<test name="Default test" duration-ms="13" started-at="2018-01-20T04:02:48Z"
			finished-at="2018-01-20T04:02:48Z">
			<class name="amazonpages.HomeAmazon">
				<test-method status="FAIL"
					signature="beforeSuite()[pri:0, instance:null]" name="beforeSuite"
					is-config="true" duration-ms="0" started-at="2018-01-20T15:02:48Z"
					finished-at="2018-01-20T15:02:48Z">
					<exception class="java.lang.NullPointerException">
						<full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:182)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
						</full-stacktrace>
					</exception> <!-- java.lang.NullPointerException -->
					<reporter-output>
					</reporter-output>
				</test-method> <!-- beforeSuite -->
				<test-method status="FAIL" signature="afterTest()[pri:0, instance:null]"
					name="afterTest" is-config="true" duration-ms="0"
					started-at="2018-01-20T15:02:48Z" finished-at="2018-01-20T15:02:48Z">
					<exception class="java.lang.NullPointerException">
						<full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:182)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.afterRun(TestRunner.java:1012)
	at org.testng.TestRunner.run(TestRunner.java:636)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
						</full-stacktrace>
					</exception> <!-- java.lang.NullPointerException -->
					<reporter-output>
					</reporter-output>
				</test-method> <!-- afterTest -->
				<test-method status="FAIL" signature="afterSuite()[pri:0, instance:null]"
					name="afterSuite" is-config="true" duration-ms="0"
					started-at="2018-01-20T15:02:48Z" finished-at="2018-01-20T15:02:48Z">
					<exception class="java.lang.NullPointerException">
						<full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:182)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:336)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
						</full-stacktrace>
					</exception> <!-- java.lang.NullPointerException -->
					<reporter-output>
					</reporter-output>
				</test-method> <!-- afterSuite -->
			</class> <!-- amazonpages.HomeAmazon -->
		</test> <!-- Default test -->
	</suite> <!-- Default suite -->
</testng-results>
